### PR TITLE
add support for Stellar Protocol 19

### PR DESCRIPTION
**Pull request by overcat**
CHANGELOG:
- add support for Stellar Protocol 19
- fix: make the app return the signature correctly in hash signing mode
- use UTC string to represent TimeBounds. (ex. 2022-03-26 03:49:59)
- when timeBounds is set to TimeBounds(0, 0), it is no longer displayed.
- display asset issuer when necessary, such as displaying asset issuer in payment operation details.
- it's annoying to confirm the tx source (and feeBumpTx source) on the Nano S, when the signing account matches the tx source, only display the summary of the tx source.
- adjusted struct field layout to reduce memory consumption.

### CODE REVIEW

**Comment by tomerweller** [comment]
What will be displayed if there is only one timebound? for example, for (0,n), will the lower limit still be displayed?

**Comment by tomerweller** [comment]
The example UTC string you shared (2022-03-26 03:49:59) doesn't have an indicator that it's not local time for the user. Maybe we can instead use [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) which is an industry standard?

**Comment by overcat** [comment]
> What will be displayed if there is only one timebound? for example, for (0,n), will the lower limit still be displayed?

I want to keep them in pairs, the following will be displayed:
```
Time Bounds From: [no restriction]
Time Bounds To: n (Time String)
```

**Comment by overcat** [comment]
> The example UTC string you shared (2022-03-26 03:49:59) doesn't have an indicator that it's not local time for the user. Maybe we can instead use [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) which is an industry standard?

Yes, I've thought about this, but the reason I chose the current format is that it fits on a single screen.

I will modify it to ISO-8601 format.

**Comment by tomerweller** [comment]
> I want to keep them in pairs

What's the value of keeping them in paris? Why not just skip displaying a timebound when there is no restriction?

**Comment by overcat** [comment]
@tomerweller 
There are currently two options for displaying time bounds, I personally prefer the latter because it can be displayed on one screen, and we indicate in the title that this is UTC time, which one do you prefer?

- option 1
screenshot_1
screenshot_2

- option 2
screenshot_3

**Comment by overcat** [comment]
> > I want to keep them in pairs
> 
> What's the value of keeping them in pairs? Why not just skip displaying a timebound when there is no restriction?

emmm, maybe it's my personal preference, I think it's not a big deal and I've skipped it.

**Comment by antb123** [comment]
Further to Tomer's tweat... the feature I would like is an option to skip all the details of the transaction.

Particularly if a transaction has a lot of operations it takes a lot of right pressing to make it happen. If I don't have a lot of funds on the device the risk is low.

**Comment by overcat** [comment]
Hi @antb123, I'm going to refactor this app soon, and I thought I'd add a new setting to it that would allow users to skip these complicated items.

**Comment by tomerweller** [comment]
> There are currently two options for displaying time bounds, I personally prefer the latter 

I agree that the latter, with `UTC` is better.

**Comment by tomerweller** [comment]
I just reviewed the current signing flow and would like to recommend a few low hanging fruit improvements:
 
- Remove `Network Public` indicator screen when using the public network - most people use their device for the public network. We can leave the testnet indicator for disambiguating test transactions. 
- Rename `Network Test` indicator to `Network Testnet` as that's the actual name    
- Remove the `Transaction Details` information prompt. This is redundant as the signing flow starts with a `Review Transaction` prompt.
- Rename timebounds. `Max Time`->`Valid Before` and `Min Time`-> `Valid After`
- Remove `Memo [none]` indicator when there's no memo.
- Rename `Fee`->`Max Fee`

**Comment by overcat** [comment]
> * Remove `Memo [none]` indicator when there's no memo.

I think we should keep it, many users forget the memo when sending to the exchange, I think this can serve as a reminder.

**Comment by tomerweller** [comment]
> I think we should keep it, many users forget the memo when sending to the exchange, I think this can serve as a reminder.

That's a good point. 

I'm on the fence about this. The role of the HW wallet's tx display is to verify that the tx you're signing is identical to the transaction you generated in the SW wallet. It's less about double checking that you generated the "right" transaction". 

With that said, missed memos are so common in Stellar that maybe it's ok keeping this around as extra security.

**Comment by tomerweller** [comment]
One more:
- For `Change Trust` operations remove `Trust Limit [maximum]` when set to max int64, this is probably more confusing than helpful.

**Pull request merged**
