### PR TITLE
New Release

### PR DESCRIPTION
**Pull request by overcat**
# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped 

You can find the changelog [here](https://github.com/lightsail-network/app-stellar/blob/80d8c1005aa9d83c490215b0c4965ea71ce42143/release-notes.md).

Resolve https://github.com/LedgerHQ/app-stellar/issues/82

### CODE REVIEW

**Comment by overcat** [comment]
Perhaps we need to disable the default CodeQL scan configuration. Otherwise, the CodeQL CI will not pass.

https://docs.github.com/en/code-security/code-scanning/troubleshooting-sarif-uploads/default-setup-enabled

**Comment by tdejoigny-ledger** [comment]
Hello @overcat , ty for your PR

Could you please open a PR to update the ledger database (https://github.com/LedgerHQ/ledger-app-database) for Stellar in order to have the guideline CI green ?
Is there any test for the new device ? I didn't find any snapshots..
Last remark, you can probably:
- use `useCaseHomeAndSettings` instead of `useCaseHome` + `useCaseSettings`
- use `useCaseAddressReview` instead of `nbgl_useCaseReviewStart` + `nbgl_useCaseAddressConfirmation`

We have a good example in our boilerplate app. It would be more simple & easier to maintain (with the guarantee to be aligned with the design guidelines)

**Comment by overcat** [comment]
Hi @tdejoigny-ledger 

> Could you please open a PR to update the ledger database (https://github.com/LedgerHQ/ledger-app-database) for Stellar in order to have the guideline CI green ?

I added it a few days ago, and now CI has passed.

> Is there any test for the new device ? I didn't find any snapshots.

We use [zemu](https://github.com/Zondax/zemu) for e2e testing, but it does not yet support Flex, so we may need to wait some time before adding it.
The other four devices all have end-to-end testing.

> Last remark, you can probably:
use useCaseHomeAndSettings instead of useCaseHome + useCaseSettings
use useCaseAddressReview instead of nbgl_useCaseReviewStart + nbgl_useCaseAddressConfirmation
We have a good example in our boilerplate app. It would be more simple & easier to maintain (with the guarantee to be aligned with the design guidelines)

I have made the corresponding modifications. Because I also want to make some changes in the UI aspect, originally I planned to submit them together at that time, but now let's first submit this part.


CodeQL test failure is likely due to repository configuration issues: https://github.com/LedgerHQ/app-stellar/pull/84#issuecomment-2114257826

**Comment by tdejoigny-ledger** [comment]
> Hi @tdejoigny-ledger
> 
> > Could you please open a PR to update the ledger database (https://github.com/LedgerHQ/ledger-app-database) for Stellar in order to have the guideline CI green ?
> 
> I added it a few days ago, and now CI has passed.
> 
> > Is there any test for the new device ? I didn't find any snapshots.
> 
> We use [zemu](https://github.com/Zondax/zemu) for e2e testing, but it does not yet support Flex, so we may need to wait some time before adding it. The other four devices all have end-to-end testing.
> 
> > Last remark, you can probably:
> > use useCaseHomeAndSettings instead of useCaseHome + useCaseSettings
> > use useCaseAddressReview instead of nbgl_useCaseReviewStart + nbgl_useCaseAddressConfirmation
> > We have a good example in our boilerplate app. It would be more simple & easier to maintain (with the guarantee to be aligned with the design guidelines)
> 
> I have made the corresponding modifications. Because I also want to make some changes in the UI aspect, originally I planned to submit them together at that time, but now let's first submit this part.
> 
> CodeQL test failure is likely due to repository configuration issues: [#84 (comment)](https://github.com/LedgerHQ/app-stellar/pull/84#issuecomment-2114257826), it is running well in my repository: https://github.com/lightsail-network/app-stellar/actions/runs/9869736057

Ok ty @overcat I will approve & merge this PR

**Review by tdejoigny-ledger — APPROVED** [review]

**Pull request merged**
